### ISSUE TITLE
[아이템 01] 생성자 대신 정적 팩터리 메서드를 고려하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#1]

**Comment by 102092** [comment]
> p9 호출될 때 마다 인스턴스를 새로 생성하지 않아도 된다.
- https://javabom.tistory.com/1 도 참고했을 때, 아마도 `static 자원은 JVM 클래스로더의 초기화 부분에서 할당된다` 문구를 통해, JVM을 통한 어떤 과정을 거치는 것 같은데, 이 부분에 대해 좀 더 설명해주실 수 있을까요??

**Comment by david215** [comment]
> > p9 호출될 때 마다 인스턴스를 새로 생성하지 않아도 된다.
> 
> * https://javabom.tistory.com/1 도 참고했을 때, 아마도 `static 자원은 JVM 클래스로더의 초기화 부분에서 할당된다` 문구를 통해, JVM을 통한 어떤 과정을 거치는 것 같은데, 이 부분에 대해 좀 더 설명해주실 수 있을까요??

저는 JVM에서 어떻게 구현했는지는 잘 모르지만 일반적으로 프로그램이 로딩될 때에 static 자원을 위한 메모리 구역을 정해놓고 미리 로딩을 해놓는 것으로 이해하고 있어요. 책에서는 Boolean.valueOf()를 예시로 사용하는데 Boolean wrapper class는 가질 수 있는 값이 true / false 두 가지 밖에 없기 때문에 미리 정적으로 할당을 해놓고 Boolean.valueOf() 호출을 할 때마다 그에 대한 레퍼런스를 반환하는 식으로 이해했습니다.

추가적으로 flyweight 패턴과 연결을 지어서 설명이 많이 되어있던데 flyweight 패턴에 대한 간단하게 정리해주시면 좋을 거 같습니다.

**Comment by wooody92** [comment]
@102092 
JVM 메모리 구조에 대한 질문을 주셨는데요. @david215 이 답변을 잘해주셨는데 조금만 더 상세히 설명하겠습니다.

우선 애플리케이션을 실행하면 아래와 같이 Java 소스파일을 읽어 Java 바이트코드로 변환시켜줍니다. 그리고 Class Loader를 통해 Runtime Data Areas에 배치가 되는데요, 여기서 Runtime Data Areas 부분을 더 상세히 살펴보겠습니다. 

<img width="749" alt="JVM2" src="https://user-images.githubusercontent.com/58318041/93234927-e0c05b80-f7b7-11ea-9e39-32805b995030.png">

Runtime Data Areas을 보면 여러 영역으로 구분이 되어있습니다. 여기서는 답변에 필요한 Heap영역과 Method 영역에 대해서만 보겠습니다.

우선 Heap 영역의 경우 보통 우리가 new로 생성하는 모든 객체들이 이곳에 저장됩니다. 그리고 그 객체를 가리키고있는 참조값(reference 또는 pointer)가 없으면 G.C에 의해 메모리에서 지워집니다.

반면에 Method 영역(class 또는 static 영역이라고도 합니다)의 경우 클래스 파일의 바이트 코드가 로드되는 영역인데요, static 자원들도 이곳에 말그대로 정적으로 저장됩니다. 그렇기 때문에 호출시마다 인스턴스를 새로 생성할 필요가 없습니다.

답변이 됐으면 좋겠네요. 잘못된 부분이 있다면 언제든 말씀해주세요.

flyweight 패턴은 제가 공부해보고 내용 공유하겠습니다.

**Comment by 102092** [comment]
@david215 @wooody92 설명 감사합니다. 어렴풋이 알았던 내용들에 대해서 이해가 된듯 해요!

> p10 2문제 단락, 자바 8 이전에는 인터페이스에서 정적 메서드를 선언할 수 없어서, 동반 클래스를 만들어서 내부에 인터페이스를 반환하는 정적 메서드를 정의했다.

이 설명에 대해 좀 더 설명해주셨으면 좋을 것 같아요.
이렇게 봐서는 어떤 의미인지 잘 이해가 안되네요. ㅠㅠ

그리고 동반 클래스 companion class가 어떤 것인지도 한번 알려주실 수 있나요?

**Comment by guswns1659** [comment]
> p.11 다섯 번째, 정적 팩터리 메서드를 작성하는 시점에는 반환할 객체의 클래스가 존재하지 않아도 된다. 

5번째 장점을 설명하면서 JDBC에 대한 예시가 나오는데 제가 이해한 내용이 맞을까요? 

반환타입을 JDBC 인터페이스로 정하면 각 데이터베이스 벤더(오라클, MySQL)가 JDBC 인터페이스를 구현하는 구체적인 클래스가 생성한다. 그렇기 때문에 정적 팩터리 메서드를 작성할 시점에는 반환할 구체적인 클래스가 존재하지 않는다. 해당 JDBC 인터페이스를 사용할 때 정해지기 때문이다. 다형성과도 관련이 있어보이네요

**Comment by wooody92** [comment]
@david215 

Flyweight 디자인 패턴의 경우 깊게 들어가는 것은 yak shaving 인 것 같아 간단하게 개념만 이해하고 아래 링크를 남겼습니다.

- Flyweight 개념

  ```
  메모리 절약을 위해 데이터를 공유해서 사용하는 패턴이다.
  공통적으로 사용되는 객체는 새로 생성해서 사용하지 않고 공유를 통해 효율적으로 자원을 활용하는 방식이다.
  한번 생성된 객체는 두번 생성되지 않고 pool에 의해 관리 및 사용된다.
  ```

[Flyweight 패턴 블로그](http://astrod.github.io/design_pattern/2017/05/07/Flywegiht-%EB%94%94%EC%9E%90%EC%9D%B8-%ED%8C%A8%ED%84%B4/)

**Comment by wooody92** [comment]
@102092 

말 그대로 이전에는 아래와 같이 인터페이스에서 정적 메서드를 선언할 수 없었습니다. 그래서 동반 클래스를 이용하여 정적 메서드를 정의했습니다.

```java
public interface TestInterface {

    // 가능
    void print();

    // 불가능
    static void staticPrint() {
        System.out.println("hello world");
    }
}
```

그러나 Java 8 이후로 인터페이스에서 정적 메서드 선언이 가능해지면서, 아래와 같이 사용이 가능 해졌습니다.

<img width="806" alt="static-method" src="https://user-images.githubusercontent.com/58318041/93464010-7f1d0000-f923-11ea-8752-622d9f5ac62e.png">


동반 클래스(companion class)의 경우 관련 정보가 많이 나오지는 않는데요, 우선 인스턴스로 만들 수 없는 클래스 정도로만 이해하시면 될 것 같습니다. (예시 - `Collections`)

출처 - [Henry 블로그](https://wooody92.github.io/effective%20java/Effective-Java-Static-Factory-Method/)

**Comment by wooody92** [comment]
@guswns1659 

질문해주신 5번째 장점같은 경우에는 저도 명확하게 이해가 안가서.. 오프라인 모임 때 같이 애기해봤으면 좋겠습니다.

**Comment by guswns1659** [comment]
## 다섯번째 장점에 대한 참고 글
- [JDBC 기본 구조 이해](https://o-jing.tistory.com/28)

**Comment by 102092** [comment]
## 동반 클래스란 무엇인가?
- Java8 이후에는 안 쓰는 느낌
- 동반이란 명명에서, 인터페이스와 같이 가는 클래스라고 생각됨.

**Comment by 102092** [comment]
## static method를 많이 쓰면 JVM 위험하지 않을까요?
- 자바 성능 튜닝을 참고하자!

**Comment by 102092** [comment]
## 공통적인 질문, 클린코드에서도 정적 팩터리 메서드를 사는 게 좋겠음.
