### ISSUE TITLE
[아이템 10] equals는 일반 규약을 지켜 재정의하라

### ISSUE THREAD

**Issue by wooody92** [java-squid/effective-java#10]

**Comment by 102092** [comment]
>p52 논리적 동치성(logical equality)...

논리적 동치성이 어떤 의미인지 조금 더 설명해주실 수 있나요?

**Comment by 102092** [comment]
아이템 외적인 질문인 것 같지만..

`lombok`에서도 어노테이션 `equals` 가 있던 것으로 기억합니다.
어떤 원리로 되어있는 지, 한번 알아보면 재밌을듯 해요....

**Comment by kses1010** [comment]
lombok `@EqualsAndHashCode` 문서
https://projectlombok.org/features/EqualsAndHashCode

**Comment by guswns1659** [comment]
> p.59 마지막 문단. 일반 Point를 반환하는 뷰(View) 메서드(아이템 6)를 public으로 추가하는 것이다. 

여기서 뷰 메서드라는게 아이템 6에서 사용했던 캐시로 사용할 static final 인스턴스를 반환하는 메서드를 의미할까요? 코드 6-2 예시와 오같은?

**Comment by guswns1659** [comment]
> p.61 두번째 문단. 예컨대 java.net.URL의 equals는 주어진 URL과 매핑된 호스트의 IP 주소를 이용해 비교한다. 호스트 이름을 IP 주소로 바꾸려면 네트워크를 통해야 하는데, 그 결과가 항상 같다고 보장할 수 없다. 

위 문장을 이렇게 이해했습니다. "URL의 ip 주소를 가져오려면 네트워크를 통해 DNS 서버에 조회해서 가져오는데 외부 네트워크를 통해 가져오는 경우 equals가 제대로 동작하지 않는다." 그런데 dns서버에 저장된 ip주소는 항상 동일할텐데 왜 이런 문제가 발생할까요?

**Comment by guswns1659** [comment]
> p.63 앞서의 CaseInsensitiveString 예처럼 ~~~ 이럴 때는 그 필드의 표준형을 저장해둔 후 표준형끼리 비교하면 훨씬 경제적이다. 

여기서 필드의 표준형이라는 게 무엇일까요??

**Comment by kses1010** [comment]
> p.61 두번째 문단. 예컨대 java.net.URL의 equals는 주어진 URL과 매핑된 호스트의 IP 주소를 이용해 비교한다. 호스트 이름을 IP 주소로 바꾸려면 네트워크를 통해야 하는데, 그 결과가 항상 같다고 보장할 수 없다.

**equals의 판단에 신뢰할 수 없는 자원이 끼어들게 해서는 안된다.**  -> 호스트 이름이 저장된 IP주소가 항상 동일하지는 않습니다. 예를 들어 서버가 여러개가 있어 하나의 도메인에 대해 라운드 로빈 dns 형태로 랜덤으로 IP를 제공하기 때문입니다. 그래서 실무에서도 종종 문제가 생긴다고 저자가 말하는듯 합니다.

**Comment by kses1010** [comment]
> p.63 앞서의 CaseInsensitiveString 예처럼 ~~~ 이럴 때는 그 필드의 표준형을 저장해둔 후 표준형끼리 비교하면 훨씬 경제적이다.

표준형(canonical form)을 stackoverflow에서 가장 쉽게 표현한 것을 찾았습니다. 
예를들어 `CaseInsensitiveString()` 의 표준형으로 저장한다면, 대문자건 소문자건 관계 없이 저장하여 비교가 더 쌉니다.
```java
private final String s;

public CaseInsensitiveString(String s) {
    //for real code probably use locale version
    this.s = s.toLowerCase();
}
```
만약 이게 아니라 그대로 비교한다면 비교값이 훨씬 비싸질 것으로 예상됩니다. 
stackoverflow에선 이걸 `equalsIgnoreCase()` 라고 표현했네요.

즉, 표준형(canonical form)이라는건 어떤 값을 넣든 그에 맞는 값으로 기준을 정하여(표준) 그 값을 주는 것 이 아닐까 예상합니다.
다른 글에서도 Set = {false, true, 1, 0} 은  Set = {false, true} 과 같다라고 말하는군요.
확실치는 않긴한데 추가 피드백 해주셔도 됩니다.

### stackoverflow 글
[표준형 이해하기 쉬운 글](https://stackoverflow.com/questions/33992000/canonical-form-of-field)
[표준형 전체적인 설명](https://stackoverflow.com/questions/280107/what-does-the-term-canonical-form-or-canonical-representation-in-java-mean)
