### ISSUE TITLE
[아이템 12] toString을 항상 재정의하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#12]

**Comment by 102092** [comment]
> p74 BigInteger, BigDecimal...

간단하게 어떤 타입의 클래스인지, 어떨때 사용되는지 알아보면 좋을듯 합니다.

**Comment by david215** [comment]
> > p74 BigInteger, BigDecimal...
> 
> 간단하게 어떤 타입의 클래스인지, 어떨때 사용되는지 알아보면 좋을듯 합니다.

Java의 primivite int type은 (-2^31, 2^31) 밖에 표현을 못 하는데 BigInteger 같은 경우는 (-2^31^31, 2^31^31)까지 표현을 할 수 있습니다. BigDecimal은 같은 경우도 float이나 double의 범위를 벗어나는 실수를 표현하는데 사용하는데 사실 더 중요한 점은 float나 double 같은 수는 컴퓨터에서 표현하는 방식이 근복적으로 floating point error를 가지고 있기 때문에 보다 더 정확한 계산을 위해서는 BigDecimal 클래스를 사용해야 합니다.

**Comment by 102092** [comment]
@david215 
1. BigInteger의 경우에는 Integer 범위의 한계 보다 좀 더 표현할 수 있고,
2. BigDecimal은 float, Double이 표현할 수 있는 범위를 벗어나 표현할 수 있을 뿐만 아니라, 정확한 계산(아마도 소수점 문제..?)을 할 수 있도록 도와주는 클래스라고 이해하면 될까요?

**Comment by kses1010** [comment]
여기서 toString의 재정의란 뜻은 `객체.toString` 이 아닌 `@Override` 하여 toString을 한다는 의미가 맞나요?

**Comment by david215** [comment]
> 여기서 toString의 재정의란 뜻은 `객체.toString` 이 아닌 `@Override` 하여 toString을 한다는 의미가 맞나요?

원래 타이틀이 Always override toString입니다. 재정의 == override

**Comment by kses1010** [comment]
> > 여기서 toString의 재정의란 뜻은 `객체.toString` 이 아닌 `@Override` 하여 toString을 한다는 의미가 맞나요?
> 
> 원래 타이틀이 Always override toString입니다. 재정의 == override

원문이 오히려 더 알기 쉽군요 파악하기 힘들때 원문과 비교하는게 더 낫네요
