### ISSUE TITLE
[아이템 13] clone 재정의는 주의해서 진행하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#13]

**Comment by 102092** [comment]
> 읽어보면 좋을 것 같은 글

- https://www.baeldung.com/java-deep-copy
- https://blueshw.github.io/2016/01/20/shallow-copy-deep-copy/

**Comment by guswns1659** [comment]
> p.80 첫번째 문단. 이 거추장스러운 코드는 CloneNotSupportedException이 사실은 비검사 예외(unchecked exception)였어야 했다는 신호(아이템 71)다.

아이템 71도 봤는데 비검사 예외처리를 이렇게 이해했는데 맞을까요? 굳이 처리할 필요가 없는 예외는 try-catch문을 사용하지 않는다. 혹은 예외가 발생하더라도 처리가 어렵다면 비검사 예외처리이다.

**Comment by wooody92** [comment]
Checked Exception과 Unchecked Exception
[https://cheese10yun.github.io/checked-exception/](https://cheese10yun.github.io/checked-exception/)

**Comment by wooody92** [comment]
clone 재정의를 자제하고, 생성자와 팩토리 메서드 메서드 패턴을 활용하자.

**Comment by 102092** [comment]
![image](https://user-images.githubusercontent.com/22140570/97779408-1fbc3c00-1bc1-11eb-88d3-0ea9b087348b.png)
