### ISSUE TITLE
[아이템 16] public 클래스에서는 public 필드가 아닌 접근자 메서드를 사용하라

### ISSUE THREAD

**Issue by david215** [java-squid/effective-java#16]

**Comment by kses1010** [comment]
> p103 자바 플랫폼 라이브러리에도 public 클래스의 필드를 직접 노출하지 말라는 규칙을 어기는 사례가 종종 있다. 대표적인 예가 java.awt.package 패키지의 Point와 Dimension 클래스다.

여기서 왜 Point와 Dimension클래스는 필드를 직접 노출한것일까요? 둘 다 java.io.Serializable 패키지의 클래스인데 io패키지라면 input, output이라서 노출한 것일까요?

**Comment by kses1010** [comment]
> p103 package-private 클래스 혹은 private 중첩 클래스라면 데이터 필드를 노출한다 해도 하등의 문제가 없다.
> p104 package-private 클래스나 private 중첩 클래스에서는 종종 필드를 노출하는 편이 낫다.

이 문구에 대한 예시를 보고 싶습니다.

**Comment by kses1010** [comment]
- 공부하면서 알게 된 사실


package-private 는 default 접근자와 같은 말이다. 
https://docs.oracle.com/javase/specs/jls/se10/html/jls-6.html#d5e10050 에서는 package-access 라는 표현을 사용한다.

**Comment by wooody92** [comment]
@kses1010 

> > p103 자바 플랫폼 라이브러리에도 public 클래스의 필드를 직접 노출하지 말라는 규칙을 어기는 사례가 종종 있다. 대표적인 예가 java.awt.package 패키지의 Point와 Dimension 클래스다.
>
> 여기서 왜 Point와 Dimension클래스는 필드를 직접 노출한것일까요? 둘 다 java.io.Serializable 패키지의 클래스인데 io패키지라면 input, output이라서 노출한 것일까요?

스택오버플로우에 해당 내용에 대한 의견들이 있어서 공유드립니다. 하나는 초기 자바에서 GUI를 그릴때 가변객체로 사용하기 위해서라는 의견이 있네요. 참고정도만 하시면 될 것 같습니다.

https://stackoverflow.com/questions/20209942/why-does-java-awt-dimension-have-public-variables

**Comment by wooody92** [comment]
@kses1010 

> > p103 package-private 클래스 혹은 private 중첩 클래스라면 데이터 필드를 노출한다 해도 하등의 문제가 없다.
> > p104 package-private 클래스나 private 중첩 클래스에서는 종종 필드를 노출하는 편이 낫다.
>
> 이 문구에 대한 예시를 보고 싶습니다.

저도 해당 부분이 잘 이해가 안가서 아이템 15에 비슷한 질문을 남겼는데요. 저는 우선 아래와 같이 이해하고 있습니다.

```java
class Item16 {
    
    private class SubClass {
        public int num = 1;
    }
    
    public int getNumber() {
        SubClass subClass = new SubClass();
        return subClass.num;
    }
}
```

**Comment by kses1010** [comment]
혹시 그렇다면 해당 클래스와 메서드를 호출하면 어떤 효과가 나는지 설명이 가능하신가요?

**Comment by 102092** [comment]
@kses1010 
https://effectiveprogramming.tistory.com/entry/package-private-class%EC%97%90-%EB%8C%80%ED%95%9C-unit-test-
%EB%B0%A9%EB%B2%95
이 자료도 한번 참고해보시면, 도움이 될듯 합니다

**Comment by kses1010** [comment]
[package private class에 대한 unit test 방법](https://effectiveprogramming.tistory.com/entry/package-private-class%EC%97%90-%EB%8C%80%ED%95%9C-unit-test-%EB%B0%A9%EB%B2%95)
