### ISSUE TITLE
[아이템 17] 변경 가능성을 최소화하라

### ISSUE THREAD

**Issue by david215** [java-squid/effective-java#17]

**Comment by 102092** [comment]
> p113.. java.util.concurrent 패키지의 CountDownLatch 클래스가 이상의 원칙을 방증한다..

- 해당 클래스가 위 원칙을 어떻게 만족하는 지 정리해보면 좋을 것 같아요!

**Comment by wooody92** [comment]
불변 클래스를 만들기 위한 설계 방법중에 하나로 책에서는 정적 팩토리 메서드를 말하는데요. 정적 팩토리 메서드는 아이템 1의 내용처럼 단점보다는 장점이 많습니다. 저는 Entity나 DTO 생성 시 습관적으로 정적 팩터리 메서드를 만들어서 사용하고 있는데, 어떻게 보면 별다른 고민없이 무분별하게 사용해왔다는 생각이 드네요. Entity나 DTO에서 정적 팩토리 메서드를 사용하는게 단점이 있을까요? 다른 분들은 어떻게 생각하는지 궁금합니다.

-> 상속이 되지 않는 것도 다른 관점에서 보면 장점이라고도 할 수 있다.

**Comment by kses1010** [comment]
@wooody92 
아이템1에서도 이야기했던거군요 [아이템1 이슈](https://github.com/java-squid/effective-java/issues/1)에서도 이야기를 했지만 하위 클래스를 만들수 없다는 점, 네이밍 통일성을 제외하곤 큰 단점은 없으니 가능하면 쓰자는게 의견이었습니다. 클린코드에서도 적극 추천하구요.
만약 정적 팩토리 메서드를 사용한다면 Entity나 DTO에서 둘 중 어디에서만 쓸지 통일성을 지켜준다면 큰 단점은 없을 듯 합니다.

**Comment by kses1010** [comment]
@102092 
### 원칙
- 클래스가 꼭 필요한 경우가 아니면 불변이어야 한다. (getter가 있다고 해서 setter를 무조껀 만들지는 말자)
- 무거운 값객체의 경우 성능때문에 어쩔수 없다면, 불변 클래스와 쌍을 이루는 가변 동반 클래스를 public 클래스로 제공하자. [아이템 67] 최적화는 신중히 하라
- 불변으로 만들 수 없는 클래스라도 변경할 수 있는 부분을 최소한으로 줄이자
- 다른 합당한 이유가 없다면 모든 필드는 private final이어야 한다.
- 생성자는 불변식 설정이 모두 완료된, 초기화가 완벽히 끝난 상태의 객체를 생성해야한다. 

### CountDownLatch란?
- 쓰레드를 N개 실행했을 때, 일정 개수의 쓰레드가 모두 끝날 때 까지 기다려야지만 다음으로 진행할 수 있거나 다른 쓰레드를 실행시킬 수 있는 경우 사용한다. 예를들어서 리스트에 어떤 자료구조가 있고, 각 자료구조를 병렬로 처리한 후 배치(batch)로 데이터베이스를 업데이트 한다거나 다른 시스템으로 push하는 경우가 있다.

- CountDownLatch를 초기화 할 때 정수값 count를 넣어준다. 쓰레드는 마지막에서 countDown() 메서드를 불러준다. 그러면 초기화 때 넣어준 정수값이 하나 내려간다. 즉 각 쓰레드는 마지막에서 자신이 실행완료했음을 countDown 메서드로 알려준다. 이 쓰레드들이 끝나기를 기다리는 쪽 입장에서는 await()메서드를 불러준다. 그러면 현재 메서드가 실행중이 메인쓰레드는 더이상 진행하지않고 CountDownLatch의 count가 0이 될 때까지 기다린다. 0이라는 정수값이 게이트(Latch)의 역할을 한다. 카운트다운이 되면 게이트(latch)가 열리는 것이다.

출처: https://imasoftwareengineer.tistory.com/100 [삐멜 소프트웨어 엔지니어]

CountDownLatch가 여기에 있는 원칙을 방증한다는 뜻이 무엇인지 모르겠습니다. 다음은 CountDownLatch 클래스 입니다.

주석은 삭제하여 보기 쉽게 했습니다.
```java
public class CountDownLatch {
    private static final class Sync extends AbstractQueuedSynchronizer {
        private static final long serialVersionUID = 4982264981922014374L;

        Sync(int count) {
            setState(count);
        }

        int getCount() {
            return getState();
        }

        protected int tryAcquireShared(int acquires) {
            return (getState() == 0) ? 1 : -1;
        }

        protected boolean tryReleaseShared(int releases) {
            // Decrement count; signal when transition to zero
            for (;;) {
                int c = getState();
                if (c == 0)
                    return false;
                int nextc = c-1;
                if (compareAndSetState(c, nextc))
                    return nextc == 0;
            }
        }
    }

    private final Sync sync;

    public CountDownLatch(int count) {
        if (count < 0) throw new IllegalArgumentException("count < 0");
        this.sync = new Sync(count);
    }

    public void await() throws InterruptedException {
        sync.acquireSharedInterruptibly(1);
    }
    
    public boolean await(long timeout, TimeUnit unit)
        throws InterruptedException {
        return sync.tryAcquireSharedNanos(1, unit.toNanos(timeout));
    }
    
    public void countDown() {
        sync.releaseShared(1);
    }

    public long getCount() {
        return sync.getCount();
    }

    public String toString() {
        return super.toString() + "[Count = " + sync.getCount() + "]";
    }
}
```

**Comment by kses1010** [comment]
여기서 원칙에 
>  무거운 값객체의 경우 성능때문에 어쩔수 없다면, 불변 클래스와 쌍을 이루는 가변 동반 클래스를 public 클래스로 제공하자. [아이템 67] 최적화는 신중히 하라.

그러나, 저희가 아이템01에서 이야기를 나눌때 동반 클래스는 Java8이후로 잘 쓰이지 않는 클래스라고 정했습니다. 그렇다면 가변 동반 클래스란건 정확하게 무엇일까요? Java8이후 부터는 동반 클래스대신 가변 동반 클래스를 쓴다고 생각하면 이해가 빠를까요?

**Comment by kses1010** [comment]
CountDownLatch는 1회성이지만 CyclicBarrior는 1회성이 아니라 카운터를 다시 리셋하여 쓴다고 합니다. 그렇다면 CountDownLatch와 비슷하지만 다시 카운터를 리셋하는 즉, 다시 초기화하니까 CyclicBarrior는 불변 클래스가 아니다라고 생각하면 될까요?

**Comment by david215** [comment]
@102092 @kses1010 
CountDownLatch는 가변 클래스입니다. 다만 언급이 된 이유는 클래스 내의 가변적인 부분을 최소화하고 또 재사용을 원천적으로 봉쇄해서 상태 변화로 인한 실수를 줄여주는 좋은 예시라서 그런 것 같네요.

**Comment by david215** [comment]
@kses1010 
> 여기서 원칙에
> 
> > 무거운 값객체의 경우 성능때문에 어쩔수 없다면, 불변 클래스와 쌍을 이루는 가변 동반 클래스를 public 클래스로 제공하자. [아이템 67] 최적화는 신중히 하라.
> 
> 그러나, 저희가 아이템01에서 이야기를 나눌때 동반 클래스는 Java8이후로 잘 쓰이지 않는 클래스라고 정했습니다. 그렇다면 가변 동반 클래스란건 정확하게 무엇일까요? Java8이후 부터는 동반 클래스대신 가변 동반 클래스를 쓴다고 생각하면 이해가 빠를까요?

동반 클래스가 어떤 개념인지 저도 잘 이해를 못 하고 있었는데 이번 아이템에서 예시를 보고 깨달음을 얻은 거 같네요. String 클래스는 불변 객체이지만 StringBuilder라는 가변 동반 객체를 사용함으로서 String 객체의 불변성은 유지하면서 가변 객체의 유연함을 취하는 전략이라고 이해를 했습니다.
