### ISSUE TITLE
[아이템 18] 상속보다는 컴포지션을 사용하라

### ISSUE THREAD

**Issue by david215** [java-squid/effective-java#18]

**Comment by kses1010** [comment]
> p121 핵심정리에서 상속은 상위 클래스와 하위 클래스가 순수한 is-a 관계일 때만 써야 한다.

여기서 순수한 is-a 관계는 어떤건지 예시를 들어주었으면 합니다. 그리고 실무에서도 과연 순수한 is-a관계가 존재하는지도 궁금합니다.

**Comment by david215** [comment]
@kses1010 
> > p121 핵심정리에서 상속은 상위 클래스와 하위 클래스가 순수한 is-a 관계일 때만 써야 한다.
> 
> 여기서 순수한 is-a 관계는 어떤건지 예시를 들어주었으면 합니다. 그리고 실무에서도 과연 순수한 is-a관계가 존재하는지도 궁금합니다.

is-a 관계는 어렵게 생각하지 않고 직관적으로 받아들이면 될 거 같습니다. 예를 들어 원은 도형이다, 정사각형은 사각형이다 이런 것들이요. 아이템에서 예시로 들었던 InstrumentedHashSet도 사실 is-a 관계처럼 보이기는 하네요. 순수한 is-a 관계여도 inheritance가 아닌 composition으로 푸는 게 더 좋은 경우들이 많은 것으로 보여집니다.

**Comment by 102092** [comment]
- 객체가 다른 객체를 들고 있는 상황이 컴포지션
- 데코레이터 패턴
