### ISSUE TITLE
[아이템 19] 상속을 고려해 설계하고 문서화하라. 그러지 않았다면 상속을 금지하라

### ISSUE THREAD

**Issue by david215** [java-squid/effective-java#19]

**Comment by wooody92** [comment]
상속받은 자식 클래스의 객체를 생성하는 경우 부모 클래스의 생성자가 먼저 실행되는 것을 인지하자.

**Comment by wooody92** [comment]
상속을 사용하려면 제약사항이 많으므로 도큐멘테이션을 정확히 하자.

**Comment by 102092** [comment]
- 상속하지 말고
- 웬만하면 wrapper class를 사용하던가
- 상속을 사용해야하면, 문서화를 잘해놓자.
- 상속관계에 있을 때, 상위 클래스의 생성자가, 하위 클래스 생성자보다 먼저 실행된다.
- 사내에서 사용할 라이브러리도 한번 만들어볼수도 있겠다..
