### ISSUE TITLE
[아이템 21] 인터페이스는 구현하는 쪽을 생각해 설계하라

### ISSUE THREAD

**Issue by david215** [java-squid/effective-java#21]

**Comment by 102092** [comment]
> p137 ...즉 모든 메서드에서 주어진 락 객체로 동기화한 후 내부 컬렉션 객체에 기능을 위임하는 래퍼 클래스다.

- 이 부분만 봐서는 정확히 어떤 역할을 하는 클래스 인지 잘 모르겠네요.
- 혹시 좀 더 쉽게 설명해주실 수 있을까요?

**Comment by wooody92** [comment]
@102092 

SynchroziedCollection 클래스는 말 그대로 Collection에 대해서 쓰레드 세이프하게 만들기 위해 `synchronized (lock) {}`으로 동기화만 시켜주는 래퍼 클래스로 이해하고 있습니다.

**Comment by wooody92** [comment]
[https://javabom.tistory.com/44](https://javabom.tistory.com/44)

**Comment by wooody92** [comment]
뮤텍스와 세마포어 [https://worthpreading.tistory.com/90](https://worthpreading.tistory.com/90)
