### ISSUE TITLE
[아이템 22] 인터페이스는 타입을 정의하는 용도로만 사용하라

### ISSUE THREAD

**Issue by david215** [java-squid/effective-java#22]

**Comment by kses1010** [comment]
java.io.ObjectStreamConstants 이 인터페이스는 왜 상수 인터페이스로 만들었을까요? 버전을 확인해보니 1.1인거 같은데 지난번에 이야기했듯이 자바 초기에는 상수 인터페이스에 대한 위험도를 인지못해서 만든 걸까요?
