### ISSUE TITLE
[아이템 23] 태그 달린 클래스보다는 클래스 계층구조를 활용하라

### ISSUE THREAD

**Issue by david215** [java-squid/effective-java#23]

**Comment by 102092** [comment]
`tagged classes` 라는 말이 조금 생소하네요.
태그 달린 클래스라는 말은, 하나의 클래스에서 여러 개의 상태를 나타낸다 라는 의미로 받아들이면 될까요?

**Comment by david215** [comment]
@102092 
> `tagged classes` 라는 말이 조금 생소하네요.
> 태그 달린 클래스라는 말은, 하나의 클래스에서 여러 개의 상태를 나타낸다 라는 의미로 받아들이면 될까요?

맞습니다. 여러 가지의 가능한 상태 중 어떤 상태인지를 태그 / 꼬리표를 달아서 표시를 하고 그 태그에 따라 객체의 성질을 바꿔서 사용하는 패턴입니다.
