### ISSUE TITLE
[아이템 25] 톱레벨 클래스는 한 파일에 하나만 담으라

### ISSUE THREAD

**Issue by david215** [java-squid/effective-java#25]

**Comment by kses1010** [comment]
실제로 여러 톱레벨 클래스를 한 파일에 담는 예시가 있는지 궁금합니다

**Comment by 102092** [comment]
@kses1010 

현재까지 제가 살펴 봤을 때 없는 것 같습니다.

또한, 책에 적혀있는 대로 하나의 파일에 여러 톱 클래스을 담을 경우, 의도치 않은 결과를 만들어낼 수 있기 때문에
그렇게 하진 않을듯 싶습니다.
