### ISSUE TITLE
[아이템 27] 비검사 경고를 제거하라

### ISSUE THREAD

**Issue by wooody92** [java-squid/effective-java#27]

**Comment by 102092** [comment]
자바봄 :  https://javabom.tistory.com/43

**Comment by david215** [comment]
제거할 수 없는 경고는 왜 생길까에 대해서 고민을 하면서 예시를 짜봤습니다.
```java
class MyStack<E> {
    private static final int DEFAULT_SIZE = 16;

    private Object[] elements;
    private int i;

    public MyStack() {
        elements = new Object[DEFAULT_SIZE];
        i = 0;
    }

    public void push(E element) {
        elements[i++] = element;
    }

    public E pop() {
        @SuppressWarnings("unchecked")
        E element = (E) elements[--i];
        return element;
    }

    private void resize(double factor) {
        int newSize = (int) (elements.length * factor);
        elements = new Object[newSize];
        // ... copying logic omitted
    }
}
```
ArrayList를 비롯한 많은 Collection 인터페이스 구현체들은 기본적으로 내부적으로 배열을 사용하고 있습니다. 위 예시를 보면 `elements`가 `Object[]`로 선언이 되어 사용되기 때문에 `pop()` 메소드에서 `@SuppressedWarnings("unchecked")` 어노테이션이 사용이 됐습니다.
<br>
그러면 처음부터 `elements`를 `Object[]`가 아닌 `E[]`로 선언하여 사용할 수는 없었을까? 라는 궁금증이 들어서 (자바봄 예시에서도 그렇게 선언이 되어있던데...) 여러가지 시도를 해보았습니다.
<br>
```java
private E[] elements;

public MyStack() {
    elements = new E[DEFAULT_SIZE]; // generic array creation error
    // ...
}
```
일단 이 방법은 제너릭 배열 생성 **에러**가 발생하기 때문에 사용할 수 없습니다.
<br><br>
```java
private E[] elements;

public MyStack() {
    @SuppressWarnings("unchecked")
    elements = (E[]) new Object[DEFAULT_SIZE];
    // ...
}
``` 
이것도 **에러**입니다. `@SuppressWarnings` 어노테이션은 변수, 함수, 혹은 클래스를 *선언*할 때만 사용할 수 있습니다. 위 예시는 변수 선언이 아닌 대입*문*입니다 (if 문, while 문의 그 문입니다).
<br><br>
```java
private E[] elements;

@SuppressWarnings("unchecked")
public MyStack() {
    elements = (E[]) new Object[DEFAULT_SIZE];
    // ...
}
``` 
차선책으로 경고 억제를 함수 선언 위에 붙이는 방법이 있는데 가장 좁은 스코프에서 경고 억제를 하라는 원칙을 지키지 못 하게 됩니다.
<br><br>
```java
@SuppressWarnings("unchecked")
private E[] elements = (E[]) new Object[DEFAULT_SIZE];

public MyStack() {
    // ...
}
```
이번에는 변수 선언에 어노테이션을 붙여서 에러가 발생하지 않습니다 (킹치웠나?)
하지만 `MyStack<E>` 객체는 `resize()`라는 메소드를 구현해야 합니다.
```java
@SuppressWarnings("unchecked")
private void resize(double factor) {
    // ...
    elements = (E[]) new Object[newSize];
    // ...
}
```
제너릭 배열은 생성이 불가능하기 때문에 이번에도 캐스팅을 해줘야 하는데 마찬가지로 선언이 아닌 대입문이기 때문에 경고 억제를 가장 좁은 스코프에서 하지 못하고 메소드 선언에서 해야만 합니다. 이상적이지는 않죠.
### 결론
- 제너릭과 배열을 같이 사용하는 경우에는 비검사 경고가 불가피하게 발생하게 된다.
- 내부적으로 사용하는 배열이 `final`한 경우를 제외하고는 그 배열의 정적 타입을 `Object[]`로 선언하는 것이 가장 좁은 스코프에서 비검사 경고 억제를 하라는 원칙을 지킬 수 있는 방법이다.

**Comment by kses1010** [comment]
아이템28에서도 나오듯이 Object[] 가 아닌 List로 하면 더 괜찮지 않을까요?

**Comment by david215** [comment]
> 아이템28에서도 나오듯이 Object[] 가 아닌 List로 하면 더 괜찮지 않을까요?

위 예시는 `Collection`을 사용하는 게 아니라 **구현**하는 거라서 상황이 좀 다르죠. `List`의 구현체가 없는데 `List`를 사용할 수는 없으니까요. 물론 우리가 일반적으로 무언가를 구현할 때는 wrapper pattern을 활용해 `Collection` 객체를 확장하는 식으로 사용하게 되니까 배열보다는 컬렉션 제너릭 객체를 사용하는 것이 자연스럽겠죠.

**Comment by 102092** [comment]
supperssing warning : https://www.baeldung.com/java-suppresswarnings
