### ISSUE TITLE
[아이템 31] 한정적 와일드카드를 사용해 API 유연성을 높이라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#31]

**Comment by 102092** [comment]
>p184 PECS..

- PECS 특히 생산자, 소비자 라는 개념이 잘 와닿지 않는 것 같습니다.
  - 인스턴스를 기준으로 구분하는 것 같긴 한데... 만약 저한테 설명해보라고 하면 못할 것 같아요..ㅠㅠ
- 다른 예를 들어서 설명해주실 수 있나요?

**Comment by guswns1659** [comment]
@102092 

다른 예시보단 생산자와 소비자에 대한 개념이 잡힌다면 쉽게 이해되실 것 같아서 제가 이해한 언어로 표현해보겠습니다. 생산자와 소비자란 표현이 자주 등장하기 때문에 중요하다 생각해서 그렇습니다. 핵심적으로는 생산자는 추가하는 역할, 소비자는 기존 원소를 사용하는 역할을 하는 객체라고 이해했습니다.

## 생산자 = 원소를 새롭게 추가하는 역할
- 매개변수가 생산하는 역할이라는 의미는 단순하게는 기존 인스턴스에 (책에서는 Stack) 새로운 원소를 추가(생산)한다는 의미이다. 그래서 기존 인스턴스에서 새로운 원소가 추가되서 문제없이 사용하려면 추가되는 원소의 타입이 기존 인스턴스의 원소 타입보다 **하위 타입**이어야 한다. 그래야 리스코프 치환이 적용되서 문제없이 사용. 

예를 들어, Stack<Animal>이라는 기존 인스턴스가 있고, 새로 추가되는 원소들이 List<Dog>라면 문제없이 스택에 추가될 수 있다. 왜냐하면 Dog는 animal을 상속한 하위타입이기 때문이다 (Dog extends Animal -> ? extends Animal) 

## 소비자 = 기존 원소를 사용하는 역할

- 매개변수가 소비하는 역할이라는 의미는 단순하게는 기존 인스턴스의 원소를 사용한다는 의미이다. 기존 인스턴스에서 기존 원소를 사용해 매개변수 리스트에 넣으려면 매개변수 리스트의 타입이 기존 인스턴스의 원소 타입보다 상위타입이어야 문제없이 들어간다.

예를 들어, Stack<Animal>이라는 기존 인스턴스가 있고, 기존 원소들이 삭제되고 특정 매개변수 리스트에 담기려면 그 특정 매개변수 리스트는 Animal 타입을 다 담을 수 있게 Animal의 상위타입이어야 한다. List<Mammal> 처럼 말이다. ( Mammal super Animal -> ? super Animal)

**Comment by kses1010** [comment]
그렇다면 생산자에선 add, push, 소비자는 pop, 등등이라고 인식하면 되나요? 그 외에는 또다른 예시가 없을까요?
