### ISSUE TITLE
[아이템 33] 타입 안전 이종 컨테이너를 고려하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#33]

**Comment by 102092** [comment]
참고하면 좋을 것 같은 포스팅
- https://homoefficio.github.io/2016/11/30/%ED%81%B4%EB%9E%98%EC%8A%A4-%EB%A6%AC%ED%84%B0%EB%9F%B4-%ED%83%80%EC%9E%85-%ED%86%A0%ED%81%B0-%EC%88%98%ED%8D%BC-%ED%83%80%EC%9E%85-%ED%86%A0%ED%81%B0/

**Comment by guswns1659** [comment]
전체적으로 어려운 주제네요. 

타입 안전 이종 컨테이너를 이렇게 이해했는데 맞을까요? 기존 컬렉션 API는 컬렉션이 다루는 타입 매개변수가 정해져 있다. ex) List<Integer> list. 타입 안전 이종 컨테이너는 내부에 map을 두어 매개변수의 타입을 키로하는 여러개의 컨테이너를 가질 수 있는 컨테이너이다?

**Comment by kses1010** [comment]
@guswns1659 
List list가 무슨 뜻인가요? 타입 안전 이종 컨테이너를 사용하는 예를 찾아보니 checkedSet, checkedList, checkedMap에서 쓰고 있더라구요.
타입 안전 이종 컨테이너 또는 타입 안전 혼종 컨테이너라고 부르기도 하네요.

```java
public static <K, V> Map<K, V> checkedMap(Map<K, V> m,
                                              Class<K> keyType,
                                              Class<V> valueType) {
        return new CheckedMap<>(m, keyType, valueType);
    }


    /**
     * @serial include
     */
    private static class CheckedMap<K,V>
        implements Map<K,V>, Serializable
    {
        private static final long serialVersionUID = 5742860141034234728L;

        private final Map<K, V> m;
        final Class<K> keyType;
        final Class<V> valueType;
```

**Comment by guswns1659** [comment]
@kses1010 
List<Integer> list 처럼 특정 타입을 지정하는 걸 의미합니다. 오타였네요. 죄송합니당
