### ISSUE TITLE
[아이템 34] int 상수 대신 열거 타입을 사용하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#34]

**Comment by guswns1659** [comment]
> p.210 세번째 문단. 열거 타입에 새로운 상수를 추가하거나 순서를 바꿔도 다시 컴파일하지 않아도 된다. 공개되는 것이 오직 필드의 이름뿐이라 정수 열거 패턴과 달리 상수의 값이 클라이언트로 컴파일되어 각인되지 않기 때문이다. 

열거 타입에 새로운 상수를 추가해도 다시 컴파일을 하지 않아도 된다는 말이 이해가 안되네요. 기존 정수 열거 패턴에서도 하나의 변수를 추가한다고 반드시 컴파일을 하는 것은 아닌 것 같은데!! 어떤 의미로 설명했을까요??

**Comment by kses1010** [comment]
Enum 활용기
https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html

**Comment by kses1010** [comment]
@guswns1659 
저도 무슨뜻인지 모르겠습니다. 컴파일러 자체를 공부해야 하는건가 싶긴하군요.
> 정수 열거 패턴과 달리 상수 값이 클라이언트로 컴파일되어 각인되지 않기 때문이다.

여기서 컴파일되어 각인된다 라는 뜻이 무슨뜻인지 모르겠네요
