### ISSUE TITLE
[아이템 36] 비트 필드 대신 EnumSet을 사용하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#36]

**Comment by 102092** [comment]
> p223 
비트 필드를 사용하면 비트별 연산을 사용해 합집합, 교집합 같은 집합 연산을 효율적으로 수행할 수 있다.

- 아마 자바의 정석이나 기본서에서 한번 봤던 것 같은데, 자바에서 비트 필드를 어떻게 이용할 수 있는지 한번 확인해보면 좋을 것 같아요.

**Comment by 102092** [comment]
> p224
...EnumSet 의 내부는 비트 벡터로 구현되었다. 원소가 총 64개 이하라면, 즉 대부분의 경우에 EnumSet 전체를 long 변수 하나로 표현하여 비트 필드에 비견되는 성능을 보여준다..

- 비트 벡터로 구성된 여부와 원소 갯수 64개 이하.. 가 어떻게 연결되는 걸까요?

**Comment by wooody92** [comment]
@102092 

> > p224
> > ...EnumSet 의 내부는 비트 벡터로 구현되었다. 원소가 총 64개 이하라면, 즉 대부분의 경우에 EnumSet 전체를 long 변수 하나로 표현하여 비트 필드에 비견되는 성능을 보여준다..
>
> - 비트 벡터로 구성된 여부와 원소 갯수 64개 이하.. 가 어떻게 연결되는 걸까요?

bit operation을 사용하는 EnumSet의 경우 원소 갯수 하나당 bit 하나(0001, 0010, ...)를 차지하는데요, 원소의 갯수가 64개 이하라면 long 자료형 8byte = 64bit이므로 long 변수 하나로 표현가능하다는 말로 이해했습니다. EnumSet을 사용해보지는 않았지만 어떤식으로 사용되는지정도는 알고가면 좋을 것 같네요.

EnumSet 참고 링크 - https://www.geeksforgeeks.org/enumset-class-java/

**Comment by wooody92** [comment]
@102092 



> > p223
> > 비트 필드를 사용하면 비트별 연산을 사용해 합집합, 교집합 같은 집합 연산을 효율적으로 수행할 수 있다.
>
> - 아마 자바의 정석이나 기본서에서 한번 봤던 것 같은데, 자바에서 비트 필드를 어떻게 이용할 수 있는지 한번 확인해보면 좋을 것 같아요.

일전에 동아리 활동으로 임베디드 개발을 한적이 있는데. 하드웨어 기반에 가까운 개발이다보니 비트단위로 레지스터 조작 등 빈번하게 사용했었는데, Java를 사용한 웹 개발에서는 비트연산을 거의 드물게 사용했던것 같네요.

**Comment by kses1010** [comment]
불변 EnumSet에 대한 stackoverflow [링크](https://stackoverflow.com/questions/49263098/is-javas-enumset-mutable/49263193)

Guava에 불변 EnumSet이 있습니다.
[Guava 불변 EnumSet](https://guava.dev/releases/snapshot/api/docs/com/google/common/collect/Sets.html#immutableEnumSet-java.lang.Iterable-)

자바 11까지 추가하지 않은걸 보아 자바 개발팀은 불필요하다고 느낀게 아니냐라는 옮긴이의 사견이 있었습니다.
