### ISSUE TITLE
[아이템 41] 정의하려는 것이 타입이라면 마커 인터페이스를 사용하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#41]

**Comment by wooody92** [comment]
~~마커 인터페이스의 경우 예시로 아래와 같이 Serializable 이 많이 나오는데, 마커 어노테이션 예시는 어떤게 있을까요? 아래 마커 인터페이스 예시를 마커 어노테이션으로도 표현할 수 있을까요? 스터디때 얘기해봤으면 좋겠습니다.~~

```java
public interface Serializable {
}
```

- 마커 인터페이스 참고 예시
  - https://woovictory.github.io/2019/01/04/Java-What-is-Marker-interface/

-> 아이템 39 : @Test 가 마커 어노테이션의 예

**Comment by wooody92** [comment]
추가로 마커의 경우도 자바 라이브러리 개발을 위해 주로 사용되는 걸까요? 저희가 웹 개발시에도 유용한 도구로도 사용 할 수 있을 것 같아서요.
