### ISSUE TITLE
[아이템 42] 익명 클래스보다는 람다를 사용하라

### ISSUE THREAD

**Issue by wooody92** [java-squid/effective-java#42]

**Comment by kses1010** [comment]
> p258
람다를 직렬화하는 일은 극히 삼가야한다.

직렬화 할 때 대부분 클래스에 Serializable을 구현할 텐데 만약 그렇다면 제가 만든 함수에 람다가 있다면 어떻게 되나요? 그걸 하나하나 private 정적 중첩 클래스의 인스턴스를 사용해야 할까요?

**Comment by wooody92** [comment]
@kses1010 
> > p258
> > 람다를 직렬화하는 일은 극히 삼가야한다.
>
> 직렬화 할 때 대부분 클래스에 Serializable을 구현할 텐데 만약 그렇다면 제가 만든 함수에 람다가 있다면 어떻게 되나요? 그걸 하나하나 private 정적 중첩 클래스의 인스턴스를 사용해야 할까요?

네. 생성한 메서드에 직렬화가 필요하다면, 해당 메서드에는 람다 또는 익명 클래스 인스턴스 사용을 삼가고 private 정적 중첩 클래스의 인스턴스를 사용해야합니다. (이펙티브 자바 책 내용에 의거)

- 왜? 람다나 익명 클래스의 경우 구현별로(가상머신 별로) 직렬화 형태가 다르기 떄문 

아래 자바봄 링크 마지막 부분에서 해당 예시를 볼 수 있습니다.

### 참고

- [자바봄 아이템 42](https://javabom.tistory.com/66)
- [우아한 형제들 자바 직렬화](https://woowabros.github.io/experience/2017/10/17/java-serialize.html)

**Comment by wooody92** [comment]
책에서 직렬화해야만 하는 함수 객체의 예시로 나온 Comparator의 경우는 왜 직렬화가 필요할까요? 제가 이해한 바로는 자바 직렬화를 사용하는 이유는 자바 시스템간의 데이터 교환을 위해서로 알고있는데 비교기의 경우에는 왜 직렬화가 필요한지 의문이 드네요.
