### ISSUE TITLE
[아이템 47] 반환 타입으로는 스트림보다 컬렉션이 낫다

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#47]

**Comment by 102092** [comment]
> code 47-6, 47-7

해당 코드는 조금 이해가 어려운 것 같아요.
같이 어떻게 진행되는 지 되짚어보면 좋을 것 같습니다!

**Comment by david215** [comment]
@102092 
그냥 알고리즘 문제라서 미팅 시간에 간단하게 훑고 넘어갈게요
