### ISSUE TITLE
[아이템 49] 매개변수가 유효한지 검사하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#49]

**Comment by kses1010** [comment]
제가 너무 늦게 질문드리는 군요.
Spring에서는 validation으로 매개변수 유효에 대하여 검사할 수 있는데 그것보다 이것을 꼭 써야하는 이유를 알 수 있을까요?
제생각엔 예전에 토비의 스프링에서 읽었던 POJO(간단한 자바 오브젝트)를 만들기 위해서 validation보단 assert, requireNonNull 등을 써야하지 않나? 라는 생각입니다. 여기에 대해선 어떻게 생각하는지 궁금합니다.

**Comment by 102092** [comment]
@kses1010 

꼭 써야할 이유는 없을 것 같아요.

그렇지만 Spring에서 `@valid` 라는 어노테이션을 만들어 놓은 건, 더 쉽고 다양하게 유효성 검사를 할 수 있기 때문이지 않을까 싶어요.
