### ISSUE TITLE
[아이템 05] 자원을 직접 명시하지 말고 의존 객체 주입을 사용하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#5]

**Comment by 102092** [comment]
> p29 Supplier<T>를 입력받는 메서드는 일반적으로 한정적 와일드 타입을 사용해 팩터리의 타입 매개변수를 제한해야한다.
1. java8에서 나온 Supplier라는 인터페이스에 대해 간단하게 나마 설명해주시면 감사하겠습니다!

2. 한정적 와일드 타입을... 이건 아마도 `Supplier<? extends Tile>` 코드를 설명하는 것 같은 데 제가 이해한 바로는 `Tile` 클래스를 상속받는 클래스라면 모든지 가능하다? 라는 의미같은 데, 아마도 1번의 설명과 맞물려서 ... 한번 이야기해보면 좋을듯 합니다.

**Comment by david215** [comment]
> 1. java8에서 나온 Supplier라는 인터페이스에 대해 간단하게 나마 설명해주시면 감사하겠습니다!

Supplier 인터페이스만 분리해서 보기 보다는 전체적인 functional interface의 구조를 보면 자연스럽게 이해가 될 거 같네요. [java.util.function](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/util/function/package-summary.html)에서 가장 대표적인 개념들을 꼽아보자면
- `Function<T, R>` - 타입 T의 인풋을 받아서 타입 R의 아웃풋을 반환
- `Consumer<T>` - 타입 T의 인풋을 받고 아웃풋 x
- `Supplier<T>` - 인풋 x,  타입 T의 아웃풋을 반환
- `Predicate<T>` - 타입 T의 인풋을 받아 boolean 값을 반환

> 2. 한정적 와일드 타입을... 이건 아마도 `Supplier<? extends Tile>` 코드를 설명하는 것 같은 데 제가 이해한 바로는 `Tile` 클래스를 상속받는 클래스라면 모든지 가능하다? 라는 의미같은 데, 아마도 1번의 설명과 맞물려서 ... 한번 이야기해보면 좋을듯 합니다.

이해하신 것이 맞습니다. Supplier를 사용해 의존 객체 주입을 사용할 때 한정적 와일드 타입을 사용함으로써 하위 클래스의 객체를 주입하는 것을 가능하게 해주기 위해 사용한다고 이해하면 되겠네요.

**Comment by guswns1659** [comment]
> p.30 의존 객체 주입이라 하는 이 기법은 클래스의 유연성, 재사용성, 테스트 용이성을 기막히게 개선해준다. 

외부에서 객체를 주입받는 기법이 내부에서 객체를 생성해서 할당하는 방식에 비해 유연성, 재사용성, 테스트 용이성에 유리하다고 하는데 왜 그런지 각 키워드 별로 간단히 설명해주시면 감사하겠습니다! 

- Random 객체를 주입 받아서, 호눅스가 쓴 것

**Comment by 102092** [comment]
## Q) 스프링에서 필드 주입을 왜 deprecated하는가?
- 확장성, 재사용성 문제인듯
- A인터페이스가 있고, 이를 구현한 B,C,D 구현체가 있다고 가정할 때, A 인터페이스를 필드에 선언해놓고 필드 주입한다면, A만 받을 수 있음.
- 반면에 생성자 주입을 하면, 선언은 A 인터페이스로 하고, B,C,D 중 원하는 것으로 주입 받을 수 있음.

**Comment by 102092** [comment]
## Q) 사용하는 자원에 따라 동작이 달라지는 클래스에는 정적 유틸리티 클래스나 싱글턴 방식이 적합하지 않다 건 무슨말일까?
- Dictionary이 변하면 spellchecker도 달라져야 하는 데, 그게 불가능하다.
- 유틸리티 클래슨, 싱글턴 방식을 착용하면 확장성이 없다.
