### ISSUE TITLE
[아이템 53] 가변인수는 신중히 사용하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#54]

**Comment by 102092** [comment]
> p322.. EnumSet 정적 팩터리...

![image](https://user-images.githubusercontent.com/22140570/105184260-7eff6c00-5b72-11eb-9fd3-398371f57ee1.png)
- https://docs.oracle.com/javase/8/docs/api/java/util/EnumSet.html
- 신기하네요!

**Comment by ghojeong** [comment]
EnumSet 에 관한 공식문서 링크 감사합니다. 53 아이템을 관통하는 핵심 같습니다.

**Comment by ghojeong** [comment]
`5개 미만(0개부터 4개까지)의 가변 인수에 대해서는 오버로딩을 통한 최적화를 해주는게 좋다.`

아이템 53 내용은 위의 한 문장으로 요약하면 될것 같습니다.
