### ISSUE TITLE
[아이템 55] 옵셔널 반환은 신중히 하라

### ISSUE THREAD

**Issue by 102092** [java-squid/effective-java#56]

**Comment by 102092** [comment]
> 추가적으로 읽어볼만한 글!
-  http://homoefficio.github.io/2019/10/03/Java-Optional-%EB%B0%94%EB%A5%B4%EA%B2%8C-%EC%93%B0%EA%B8%B0/

**Comment by kses1010** [comment]
# Optional 사용할 때 주의할 점 정리

사실상 위 링크에서 이 아이템에 대하여 제대로 정리한 글이라고 생각합니다.

1. isPresent()-get() 대신 orElse()/orElseGet()/orElseThrow()

2. orElse(new ...) 대신 orElseGet(() -> new ...)

3. 단지 값을 얻을 목적이라면 Optional 대신 null 비교

4. Optional 대신 비어있는 컬렉션 반환

5. Optional을 필드로 사용 금지

6. Optional을 생성자나 메서드 인자로 사용 금지

7. Optional을 컬렉션의 원소로 사용 금지

8. of(), ofNullable() 혼동 주의

9. Optional<T> 대신 OptionalInt, OptionalLong, OptionalDouble
