### ISSUE TITLE
[아이템 57] 지역변수의 범위를 최소화하라

### ISSUE THREAD

**Issue by kses1010** [java-squid/effective-java#59]

**Comment by ghojeong** [comment]
아이템 57은 요약하자면 아래 3가지이네요.
크게 어려운게 없어서, 질문이 적으실것 같습니다.

1. 지역 변수를 가장 처음 쓰일 때 선언하라.
2. 지역 변수를 선언과 동시에 초기화 하라.
3. 메서드를 작게 만들고, SRP 를 지켜라
