### ISSUE TITLE
[아이템 60] 정확한 답이 필요하다면 float와 double은 피하라

### ISSUE THREAD

**Issue by kses1010** [java-squid/effective-java#62]

**Comment by 102092** [comment]
- BigDecimal docs : https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html
- BigDecimal가 어떻게 사용되는 지에 대해 : https://www.baeldung.com/java-bigdecimal-biginteger

**Comment by ghojeong** [comment]
아이템 60을 요약하자면, "돈을 계산할 때는 float 와 double 을 금지하고, BigDecimal 을 사용해라" 이군요.

BigDecimal 에 대해서 공부해봐야할 것  같은데, 좋은 문서 링크 감사합니다.
