### ISSUE TITLE
[아이템 63] 문자열 연결은 느리니 주의하라

### ISSUE THREAD

**Issue by kses1010** [java-squid/effective-java#65]

**Comment by tmdgusya** [comment]
이 분이 두개의 차이점을 메모리적인 부분을 그래프로 나타내서 설명했더라고요.
참고하면 좋을 것 같아서 링크 걸어두겠습니다!
https://javacan.tistory.com/entry/41

**Comment by 102092** [comment]
https://redfin.engineering/java-string-concatenation-which-way-is-best-8f590a7d22a8

이 포스팅도 읽을만한 것 같습니다~
