### ISSUE TITLE
[아이템 66] 네이티브 메서드는 신중히 사용하라

### ISSUE THREAD

**Issue by ghojeong** [java-squid/effective-java#68]

**Comment by kses1010** [comment]
백기선님 [더 자바] 인강에서 왈...
> 지금까지 native 메서드를 사용만 해봤지(ex: `Thread.currentThread()`) 직접 만든 적은 없다.

네이티브 메서드를 좀 더 알기 위해서 JVM의 JNI에 대해 공부해야겠네요.
[A Simple Java Native Interface (JNI) example in Java and Scala](https://schlining.medium.com/a-simple-java-native-interface-jni-example-in-java-and-scala-68fdafe76f5f)

**Comment by 102092** [comment]
네이티브 메서드의 주요 쓰임세 중에, 1번인 '레지스트리 같은 플랫폼 특화 기능' 이란 무엇을 의미하는 걸까요?

**Comment by david215** [comment]
@102092 
좀 검색을 해보긴 했는데 잘 모르겠네요. 
윈도우에 regedit으로 볼 수 있는 그런 걸 얘기하는 걸까요...? 흠

**Comment by david215** [comment]
예전에 아이템 8에서 [JNI 코드 예시](https://github.com/java-squid/effective-java/commit/b2de5e9f9f58904ad1bfbec39a3e95f4fff0b1bb)를 만들어 본 적이 있는데 심심하면 참고해보세요.
