### ISSUE TITLE
[아이템 68] 일반적으로 통용되는 명명 규칙을 따르라

### ISSUE THREAD

**Issue by ghojeong** [java-squid/effective-java#70]

**Comment by kses1010** [comment]
구글 자바 스타일 가이드
네이밍 원본: https://google.github.io/styleguide/javaguide.html#s5-naming
번역: https://velog.io/@new_wisdom/JAVA-Google-Java-Style-Guide-%EB%B2%88%EC%97%AD

**Comment by 102092** [comment]
재밌네요. 평소에 명명에 있어 모호했던 부분들에 도움이 될 듯 합니다 👍

**Comment by 102092** [comment]
https://naver.github.io/hackday-conventions-java/#class-noun
