### ISSUE TITLE
[아이템 69] 예외는 진짜 예외 상황에만 사용하라

### ISSUE THREAD

**Issue by ghojeong** [java-squid/effective-java#71]

**Comment by kses1010** [comment]
스프링의 Exception 전략(프로젝트 할 때 큰 도움이 됨)
https://cheese10yun.github.io/spring-guide-exception/

**Comment by 102092** [comment]
p388 지침 3가지에 대해 이해해보고 있는데 잘 안되네요.
그래서 어떤 예시 코드가 있을지 생각해보고 있는데... 잘 안 떠오르네요.
한번 같이 생각해보면 좋을 것 같아요!

**Comment by kses1010** [comment]
자바의 예외처리
https://johngrib.github.io/wiki/java-exception-handling/#from-%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C-%EC%9E%90%EB%B0%94

**Comment by david215** [comment]
EAFP vs LBYL에 대한 [스택 오버플로우 포스트](https://stackoverflow.com/a/405220)
