### ISSUE TITLE
[아이템 71] 필요 없는 검사 예외 사용은 피하라

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#73]

**Comment by 102092** [comment]
스트림에서 검사 예외를 던지는 메서드를 사용할 수 없다에 대해 찾아보다가 재밌는 포스팅을 발견했습니다~
https://www.baeldung.com/java-lambda-exceptions

**Comment by 102092** [comment]
checked expection를 어떻게 다뤄야할지에 대해 읽어볼만한 포스팅입니다.
https://cheese10yun.github.io/checked-exception/
