### ISSUE TITLE
[아이템 72] 표준 예외를 사용하라 

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#74]

**Comment by 102092** [comment]
이 아이템을 읽으면서 아래 포스팅도 참고하시면 도움이 될 듯 합니다.
https://www.baeldung.com/java-common-exceptions

**Comment by 102092** [comment]
> p398 인수값이 무엇이었든 어차피 실패했을 거라면.. IllegalStateException.. 그렇지 않으면 IllegalArgumentException을 던지자

두 예외에 대한 차이를 언급해준 면이 재밌네요
