### ISSUE TITLE
[아이템 73] 추상화 수준에 맞는 예외를 던져라

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#75]

**Comment by 102092** [comment]
> p339 상위계층에서는 저수준 예외를 잡아 자신의 추상화 수준에 맞는 예외로 바꿔 던저야 한다..

여기서 '저수준 예외'는  Exception 같은 예외가 아닌, 이 하위인 발생할 수 있는 특정 예외를 말하는 것이고,
'추상화 수준에 맞는 예외' 란 구체화된 에러 혹은 커스텀 에러를 던지라는 말 같은데 제가 이해한바가 맞을까요?
