### ISSUE TITLE
[아이템 76] 가능한 한 실패 원자적으로 만들라

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#78]

**Comment by 102092** [comment]
https://stackoverflow.com/questions/29842845/what-is-failure-atomicity-used-by-j-bloch-and-how-its-beneficial-in-terms-of-i
failure-atomic에 대한 간단한 글입니다. 
해당 아이템에서 잘 설명해주고 있어서 굳이 안 읽어봐도 될듯 하지만, 이 포스팅은 좀 더 간단하게 설명해주고 있는 것 같네요

**Comment by tmdgusya** [comment]
아이템 17 내용과 연관지어서 읽어도 좋을내용이네요
