### ISSUE TITLE
[아이템 08] finalizer와 cleaner 사용을 피하라

### ISSUE THREAD

**Issue by wooody92** [java-squid/effective-java#8]

**Comment by david215** [comment]
일단 finalizer가 뭔지 쉽게 설명해주는 글 [A Guide to the finalize Method in Java](https://www.baeldung.com/java-finalize)

**Comment by kses1010** [comment]
네이티브 피어가 정확하게 어떤건가요? 일반 자바 객체가 네이티브 메서드를 통해 기능을 위임한다는 뜻이라는데 이게 정확하게 무엇을 의미하는지 모르겠습니다. 여기에 관해서 예시와 쓰는 이유를 알려주셨으면 합니다!

**Comment by kses1010** [comment]
책에 있는 코드는 자바9의 cleaner를 사용했는데 finalizer를 쓸 땐 어떤 차이점이 있나요?

**Comment by kses1010** [comment]
>자바 라이브러리의 일부클래스는 안전망 역할의 finalizer를 제공한다. 

FileInputStream, FileOutputStream은 확인 결과 finalize()에서 close()메서드를 호출하는데 ThreadPoolExecutor는 close()가 없습니다. 여긴 어디서 안전망 역할을 하는걸까요? 궁금합니당

**Comment by david215** [comment]
> 네이티브 피어가 정확하게 어떤건가요? 일반 자바 객체가 네이티브 메서드를 통해 기능을 위임한다는 뜻이라는데 이게 정확하게 무엇을 의미하는지 모르겠습니다. 여기에 관해서 예시와 쓰는 이유를 알려주셨으면 합니다!

간단하게 설명하면 네이티브 피어는 C/C++이나 어셈블리 프로그램을 컴파일한 기계어 프로그램를 지칭하는데 이를 라이브러리로써 자바 피어가 실행할 수 있게 해주는 인터페이스를 JNI (Java Native Interface)라고 합니다. 자바 피어가 로딩될 때 정적으로 System.loadLibrary() 메소드를 호출해 네이티브 피어를 로딩하고 네이티브 메소드는 native 키워드를 사용해 호출하는 방식으로 사용합니다. 

[예시](https://github.com/java-squid/effective-java/commit/e305fa90d339b50ff3fefaee9caf4ac0b0d5b149)를 만들어봤으니 풀 해서 실행해보시면 좋을 거 같습니다. 실행하는 방법은 README에 적어놨습니다.

우리가 사용하는 라이브러리는 99.9% 이상 maven central에서 가져올 자바 라이브러리라 사실 우리가 JNI를 쓸 일은 거의 없을 거 같기는 합니다...

[Guide to JNI (Java Native Interface)](https://www.baeldung.com/jni)

**Comment by kses1010** [comment]
만든 사람에겐 미안하지만 정말 끔찍한 거군요

**Comment by 102092** [comment]
@david215 
네이티브 객체는 C, 어셈플리어로 만들어진 프로그램이고 이러한 프로그램이 JNI를 통해서 Java 플랫폼에서 사용될 수 있도록 만들어준다고 이해하면 될까요?
아 그리고 JVM공간 중에 Natvie Method란 공간이 있었던 걸로 기억하는데, 이곳이 Native Peer가 올라가는 공간일까요?

**Comment by david215** [comment]
> 네이티브 객체는 C, 어셈플리어로 만들어진 프로그램이고 이러한 프로그램이 JNI를 통해서 Java 플랫폼에서 사용될 수 있도록 만들어준다고 이해하면 될까요?
> 아 그리고 JVM공간 중에 Natvie Method란 공간이 있었던 걸로 기억하는데, 이곳이 Native Peer가 올라가는 공간일까요?

![image](https://user-images.githubusercontent.com/12704057/94146626-29aa9b00-feaf-11ea-981d-92b23f6e4628.png)
Runtime data area에 native method가 사용하는 스택 공간이 따로 있기는 한데 native peer, 그 프로그램 자체는 따로 정적으로 할당되는 공간이 있는 것으로 보이네요.

[The JVM Architecture Explained](https://dzone.com/articles/jvm-architecture-explained)

**Comment by 102092** [comment]
@david215 
Native Method Stack은 메서드등의 정보를 기록하는 공간이군요. 말씀하신 것처럼, native peer의 경우 할당되는 공간이 있을 것 같네요..
하지만 여기서 더 찾는 다면, 너무 깊게 들어가는 것이 아닌가 싶네요.. ㅋㅋㅋ
답변 감사합니다 👍
