### ISSUE TITLE
[아이템 78] 공유 중인 가변 데이터는 동기화해 사용하라

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#80]

**Comment by tmdgusya** [comment]
읽기전 참고하면 좋은 글입니다.

https://parkcheolu.tistory.com/14

**Comment by tmdgusya** [comment]
자바 메모리 모델에 관련된 좋은글!

https://medium.com/@qwefgh90/jsr-133-java-memory-model-faq-%EB%B2%88%EC%97%AD-128487aebc1e

**Comment by 102092** [comment]
> 읽기전 참고하면 좋은 글입니다.
https://parkcheolu.tistory.com/14

조금 읽기 어려운 아이템 같은데, 이 글과 같이 보니까 도움이 되네요! 감사합니다

**Comment by tmdgusya** [comment]
> long Double 은 원자적 수행을 보장하지 못한다에 대한 간단 요약해본 내용

long 과 double 혹은 dynamic-computed constant 의 경우 constant pool 에서 해당 index 를 참조하여 가져오는 과정이 포함되어 있어서 해당 과정에서 다른 Thread 가 끼어들 수 있기에 원자적 수행을 보장하지 못한다고 생각하는게 좋지 않을까 싶다.

실제로 byte Code 상에서 ldc2_w 라는 로직을 추가적으로 진행하는데 해당 내용이 위의 내용이다.
