### ISSUE TITLE
[Opinion] 이펙티브 자바 다음 스터디 아이템 추천하기

### ISSUE THREAD

**Issue by kses1010** [java-squid/effective-java#81]
답글로 아무 의견 부탁드립니다.

**Comment by kses1010** [comment]
저의 의견
1. 스프링을 하겠다 -> 토비의 스프링
2. 알고리즘을 하겠다 -> 알고리즘(로버트 세지윅) -> 최종목표: 코드 포스 랭크 그래이(Wls)에서 블루까지(회사 코테 다 뚫는 마지노선)
3. 자바 병렬 프로그래밍 -> 브라이언 게츠 저서 [자바 병렬 프로그래밍](http://www.yes24.com/Product/Goods/3015162) 자바의 병렬 프로그래밍 도서하면 이 책을 추천을 많이 함. 다만 번역서는 평이 좋지 않음.
4. 클린코드 or 클린 소프트웨어(로버트 C. 마틴) -> 저는 클린 소프트웨어 추천합니다. 책 내용에 애자일, TDD, 패턴까지 전부 아우르는 내용이 있으며 예시도 적절합니다.

**Comment by kses1010** [comment]
5. 오브젝트 또는 객체 지향 관련 도서를 통한 객체 지향 스터디

**Comment by tmdgusya** [comment]
1. 토비의 스프링 1권 
2. HTTP 완벽 가이드
3. DB 스터디 -> 흐음 그런데 이건 너무 애매할것 같기도해서 하네요. 책 같은 경우에도 무언가 같이 공유해서 공부할 수 있을까? 라는 생각이 드네요. 저희가 성능 튜닝 정도까지 가지 않는이상?

**Comment by ghojeong** [comment]
> HTTP 완벽 가이드

저는 개인적으로 `HTTP 완벽 가이드` 는 비추합니다. 책도 구매해서 읽어봤는데 별로 재미도 없고 졸립니다.
차라리 소켓 프로그래밍 쪽을 공부해서 연습해보거나 (요즘 핫한 웹소켓을 활용한 WebRTC 라던가),
네트워크 이론 자체를 공부하는게 좋지 않을까 싶습니다.

DB 스터디 같은 경우는 Sunny 님이 추천하신 무지개 곰돌이 책이나,
David 님이 지금 한참 수업듣고 계시는 버클리 대학의 수업자료 공유해서 복습하면 어떨지 제안해봅니다.
어차피 David 님 중간고사나 기말고사 준비하실 것 같은데,
준비하는 겸 저희랑 수업내용 다시 복습하면 좀 더 깊게 공부할 수 있지 않을까요?
물론 공유로 인해 저작권 문제가 있을 경우에는 발언 취소하겠습니다.

**Comment by ghojeong** [comment]
@kses1010  의견을 참고해서, 저도 책 정리해봅니다.

1. 스프링 -> <토비의 스프링>
2. 알고리즘 -> 종만북 <알고리즘 문제 해결 전략> (코드 포스 랭커에 도전하는 거 저도 흥미가 돋네요)
3. 객체지향 -> 조영호의 <오브젝트>
4. DDD -> 에릭 에반스의 <도메인 주도 설계>
5. 클린 소프트웨어 > 클린 아키텍처 > 클린 코드 (왼쪽이 더 읽고 싶은 책이네요)

**Comment by tmdgusya** [comment]
요즘 개인적으로 알고리즘이 뭔가 재밌네요 ㅋㅋㅋ 알고리즘 풀다가 자바언어를 더 공부하게 되는 느낌?

**Comment by kses1010** [comment]
알고리즘이면 역시 로버트 세지윅의 알고리즘 추천! 자바로 되어있으니 자바랑 알고리즘과 두마리 토끼를 잡을 수 있습니다

**Comment by 102092** [comment]
원래 스터디 마감일이 4월 11일 입니다.
그래서 가능한 4~5월 중으로 마무리 될 수 있는 주제를 잡으면 좋겠다는 생각이 들었습니다.

1.  [백기선 자바 스터디](https://www.youtube.com/watch?v=peEXNN-oob4&list=PLfI752FpVCS96fSsQe2E3HzYTgdmbz6LU)
- 현재 12주차 정도 진행되고 있는데, 한번 처음부터 따라갔으면 합니다. (저희는 한주에 2주정도 분량을 목표로..)
- 너무 어렵지 않으면서, 자바 기본을 다질 수 있는 기회가 되지 않을까 생각합니다.
- 교보재 (유투브) +  다른 분들 것도 참고 가능..하다는 이점이 있습니다.

2. [리팩토링](https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=236186172)
- 코드를 작성하면서 이해할 수 있을 거라는 생각에 골랐습니다.
- 객체지향, 클린 아키텍쳐등등을 모두 경험할 수 있지 않을까 기대하고 있습니다.

**Comment by tmdgusya** [comment]
오 개인적으로 백기선님 자바 스터디 좋다고 생각됩니다.
예전부터 한번 해봐야지 했었는데, 이번 스터디로 하게되면 괜찮을 것 같다고 저는 생각합니다

**Comment by ghojeong** [comment]
깊게 공부하고 싶은 주제 

1순위: DB (혼자서는 잘 안된다. 특히 트랜잭션 관련해서 이론적으로 깊게 공부할 필요성을 느낀다.)
2순위: k8s (인프라 관련 지식)
3순위: 코틀린 (자바 개발자로서, 공부해두면 좋지 않을까)

**Comment by tmdgusya** [comment]
어제 이야기 듣다보니 저는 오브젝트라는 책을 해보고 싶긴하네요.
개인적으로 코드들도 많고, 객체지향에 관한 내용들을 담고 있어서 스터디 해보고 싶네요.

**Comment by ghojeong** [comment]
오늘 문득 생각이 들었는데, "토비의 스프링" 1권 완독하는거 다같이 도전해보면 어떨까 합니다.
결국 Spring 으로 경력을 쌓을 거면 필독서 인것 같은데, 혼자서는 도저히 읽을 엄두가 나지 않아서요.

**Comment by tmdgusya** [comment]
> 오늘 문득 생각이 들었는데, "토비의 스프링" 1권 완독하는거 다같이 도전해보면 어떨까 합니다.
> 결국 Spring 으로 경력을 쌓을 거면 필독서 인것 같은데, 혼자서는 도저히 읽을 엄두가 나지 않아서요.

저도 개인적으로 토비의 스프링을 공부해보면 좋겠다라는 생각이 드네요. 저거 혼자서 하려니 숨이 턱턱막힙니다. 개인적으로 4장까지 한번 했었는데 잘 기억도 안나고, 같이하면 확실히 좋을 것 같네요!

**Comment by ghojeong** [comment]
전 토비의 스프링 최종 확정입니다.

**Comment by 102092** [comment]
최종!

- 백기선 자바 스터디

**Comment by tmdgusya** [comment]
최종
- 토비 스프링 6장(AOP 포함) 정도까지?

**Comment by kses1010** [comment]
최종
- 토비의 스프링
- 오브젝트
둘 중에 아무거나 가능
