### ISSUE TITLE
[아이템 82] 스레드 안전성 수준을 문서화하라

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#85]

**Comment by 102092** [comment]
문서화는 항상 중요하다고 생각하지만.. 일반 서비스정도 에서도 스레드 안전성에 대해 문서화를 하는게 필요할까요?
어떻게 생각하시는 지 이야기 나눠보면 좋을 것 같습니다!

**Comment by tmdgusya** [comment]
@102092 이 부분은 조금 애매한것 같네요. 라이브러리라면 명시해주는것이 좋을것 같은데..
근데 좋을수도 있다고 생각하는것이, 문제가났을때 해당 어노테이션이나 문서자료를 보고 해당 조건에의해 문제가 발생하는지
알수 있을것 같아서 좋은 방향이라고 생각합니다.
