### ISSUE TITLE
[아이템 83] 지연 초기화는 신중히 사용하라

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#86]

**Comment by 102092** [comment]
지연 초기화하니, spring에 lazy loading에 대해 생각이 나네요!
- https://www.baeldung.com/spring-boot-lazy-initialization
- https://www.baeldung.com/hibernate-lazy-eager-loading
이 두가지가 지연 초기화에 대해 조금 더 알아보기 좋아보입니다!

**Comment by 102092** [comment]
> volatile 을 언제 사용하는 걸까?
synchronize 를 사용해도 volatile을 사용해하는 걸까..?
- 이전 아이템에서 나온 부분인데, 읽다보니 다시 궁금해졌습니다. 
- 다시 정리해보려 합니다!

**Comment by 102092** [comment]
- https://link.springer.com/content/pdf/10.1007/3-540-45739-9_5.pdf
- 1,2페이지!

**Comment by tmdgusya** [comment]
David 이 Study 중 올렸던 링크
https://link.springer.com/content/pdf/10.1007/3-540-45739-9_5.pdf
