### ISSUE TITLE
[아이템 84] 프로그램의 동작을 프로세스 스케줄러에 기대지 말라

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#87]

**Comment by 102092** [comment]
운영체제 마다 프로세스 스케쥴러가 스레드를 다루는 방식이 다를 수 있으니..
개발자는 이런 정책에 좌우대지 않는 프로그램을 만들어야하고,
이를 위해서는 실행 가능한 평균적인 스레드 수를, 프로세서 수보다 지나치게 만들지 않도록 해야한다..가 핵심인듯 한데
맞을까요?

**Comment by david215** [comment]
> 운영체제 마다 프로세스 스케쥴러가 스레드를 다루는 방식이 다를 수 있으니..
> 개발자는 이런 정책에 좌우대지 않는 프로그램을 만들어야하고,
> 이를 위해서는 실행 가능한 평균적인 스레드 수를, 프로세스 수보다 지나치게 만들지 않도록 해야한다..가 핵심인듯 한데
> 맞을까요?

말씀하신게 맞다고 생각합니다. 덧붙이자면 "실행 가능"한 스레드들이 유의미한 일들을 하고 있어야겠죠. 예시에 나오는 SlowCountDownLatch처럼 busy-waiting을 하고 있으면 안 되고요.
