### ISSUE TITLE
[아이템 85] 자바 직렬화의 대안을 찾으라

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#88]

**Comment by 102092** [comment]
> p450 분산객체..
- 분산 객체란 말이 나오는데 어떤 의미일까요?

**Comment by 102092** [comment]
자바 직렬화에 대해 전반적으로 이해하는데 도움이 될 것 같습니다.
- https://ryan-han.com/post/java/serialization/

**Comment by tmdgusya** [comment]
> > p450 분산객체..
> 
> * 분산 객체란 말이 나오는데 어떤 의미일까요?

하나의 프로세서나 컴퓨터에서 실행되는 객체가 다른 프로세서나 컴퓨터에서 객체와 통신이 가능 하도록 하는 기술이 분산 객체 기술 이라고 하네요. 쉽게 얘기하면 직렬화 자체가 다른 JVM 과 통신할 수 있도록 하는 것이니..

아래 참고글입니다.

http://ojc.asia/bbs/board.php?bo_table=LecJavaNet&wr_id=12

**Comment by tmdgusya** [comment]
이번장은 사실 뭔가 배우기 보다는, **직렬화는 사용하지말고 JSON 같은 하나의 통신 형태 방법들로 통신해!** 라는 느낌이 강하네요.

**Comment by kses1010** [comment]
여기서 프로토콜 버퍼는 gRPC를 이야기하는 것 같군요.
