### ISSUE TITLE
[아이템 86] Serializable 을 구현할지는 신중히 결정하라

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#89]

**Comment by 102092** [comment]
> p457... 인스턴스 필드 값 중 불변식을 보장해야 할 게 있다면, 반드시 하위 클래스에서 finalize 메서드를 재정의하지 못하게 해야한다

- 단순히 이 문장만 봐서는 이해가 힘드네요. 이 문구는 어떤 걸 의미하는 걸까요..?

**Comment by 102092** [comment]
p457 나온 readObjectNoData method에 대해 더 이해하기 위해서, 아래 포스팅이 도움이 될 것 같습니다.
- https://stackoverflow.com/questions/7445217/java-when-to-add-readobjectnodata-during-serialization

**Comment by kses1010** [comment]
우아한 형제들 기술 블로그
https://woowabros.github.io/experience/2017/10/17/java-serialize2.html

**Comment by 102092** [comment]
- GC순간에, finalize 메서드가 실행되므로 어떤 파생적인 일이 벌어질지 모르기 때문에 하위 클래스에서 재정의하지 못하도록 해야한다.
