### ISSUE TITLE
[아이템 09] try-finally 보다는 try-with-resources를 사용하라

### ISSUE THREAD

**Issue by wooody92** [java-squid/effective-java#9]

**Comment by wooody92** [comment]
결론적으로 try-with-resource는 `try (회수가 필요한 자원) { 로직 }` 구조인데요.
소괄호에 작성한 자원은 try문이 끝나는 시점에 자동으로 close() 되어서 이런 방식으로 사용하는 것이 맞지요?

**Comment by 102092** [comment]
@wooody92 말씀하신 로직이 맞는 듯 합니다.
회수가 필요한 자원들(AutoCloseable Interface를 확장 혹은 구현한) 은 로직에서 사용이 끝나고 난 후에, 자동으로 `close()` 메서드가 호출되는 방식인듯 해요

참고 : https://www.baeldung.com/java-try-with-resources
예시 코드와 함께 추가적인 내용도 있네요. 참고하시면 책을 이해하는 데 도움이 되실듯 합니다
