### ISSUE TITLE
[아이템 88] readObject 메서드는 방어적으로 작성하라

### ISSUE THREAD

**Issue by tmdgusya** [java-squid/effective-java#91]

**Comment by tmdgusya** [comment]
간단히 읽어보면 50장의 내용과 일맥상통 하네요.

이건 역직렬화 했을때의 상황이고..

**Comment by 102092** [comment]
readObject가 역직렬화 시 하나의 생성자 역할을 하는 것 같은데, 개발자가 잘 놓칠 수 있는 부분이여서 이런 아이템이 나오지 않았나 싶네요.

**Comment by tmdgusya** [comment]
맞아요 잘 놓칠 수 있는 부분이라 나온것 같네요. 
이 경우 앞 챕터에서 나온 예제 처럼 외부로 부터의 공격을 당하기 쉬운 부분이라 그런것 같네요.
50장에서는 외부의 공격이 잘 이해가 가지 않았는데.. 이번 직렬화 장을 보니 외부에서 해당 바이트 스트림을 해킹해서 바이트를 바꾸는건지? 
여하튼 그런식으로 영향을 끼칠 수 있나보네요.
